version: "3.9"
services:
  db:
    image: postgres:15
    container_name: load-optimiser_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: load-optimiser
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d load-optimiser"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    build: .
    container_name: load-optimiser_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/load-optimiser
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    ports:
      - "8080:8080"

volumes:
  db_data: